export const ADD_VIDEOGAME = "ADD_VIDEOGAME";
export const ADD_VIDEOGAME_ERROR = "ADD_VIDEOGAME_ERROR";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const REMOVE_VIDEOGAME = "REMOVE_VIDEOGAME";
